name: Deploy to Firebase Hosting on PR

on: pull_request

jobs:
  build_and_preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest

    permissions:
      # Permissions for the GitHub token used to authenticate to Google Cloud.
      contents: "read"
      id-token: "write"

      # Permissions to enable the GitHub Checks API for Firebase Hosting
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_AUS_FORCE }}"

      - id: "secrets"
        uses: "google-github-actions/get-secretmanager-secrets@v1"
        with:
          secrets: |-
            token:projects/295994266197/secrets/PUBLIC_API_URL

      - run: npm ci

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_AUS_FORCE }}"
          expires: 30d
          projectId: aus-force
        env:
          PUBLIC_API_URL: "${{ steps.secrets.outputs.token }}"
