name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - run: npm ci

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_AUS_FORCE }}"
          channelId: live
          projectId: aus-force

  # get_google_screts:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: "read"
  #     id-token: "write"

  #   steps:
  #     - uses: actions/checkout@v3

  #     - id: "auth"
  #       name: "Authenticate to Google Cloud"
  #       uses: "google-github-actions/auth@v1"
  #       with:
  #         credentials_json: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_AUS_FORCE }}"

  #     - id: "secrets"
  #       uses: "google-github-actions/get-secretmanager-secrets@v1"
  #       with:
  #         secrets: |-
  #           apiUrl:aus-force/PUBLIC_API_URL

  #     # Example of using the output
  #     - id: "publish"
  #       uses: "foo/bar@main"
  #       env:
  #         PUBLIC_API_URL: "${{ steps.secrets.outputs.apiUrl }}"
